### PR TITLE
Bumped the deployment target to fix Carthage build issue

### PR DESCRIPTION
**Pull request by jernejstrasner**
It kept picking the iPad 2 / iOS 7.1 simulator, which is the first on the list and the framework can't be built for iOS 7.1 because of its dynamic nature.
This is a quick fix; setting the project deployment target to iOS 8, but it's not ideal, as some targets could go lower than iOS 8.0.
I'm not sure how to fix this in a more appropriate way. Maybe Carthage needs some changes (picking the right deployment version from each specific target instead of globally).

### CODE REVIEW

**Comment by nolanw** [comment]
@jernejstrasner I'd prefer not to change the project-wide deployment target as I'm afraid of breaking things for people who've dragged `HTMLReader.xcodeproj` in as a subproject and are happily building things that way.

Does this issue seem relevant? [Carthage build fails with iOS 7.1 simulator installed](https://github.com/Carthage/Carthage/issues/417)

**Comment by jernejstrasner** [comment]
@nolanw I certainly agree, I opened the pull request mostly to point it out and see if I'm not missing something. That Carthage issue certainly seems relevant. I'll research a bit and see if I find a fix for Carthage.

**Comment by nolanw** [comment]
@jernejstrasner I don't think you're missing anything, and I'm glad you found a workaround for now. Let me know what you find!

**Comment by jernejstrasner** [comment]
@nolanw fixed: https://github.com/Carthage/Carthage/pull/653

**Comment by nolanw** [comment]
Yay! And thank you @jernejstrasner for reporting back!

**Pull request closed without merging**
