### PR TITLE
using '/>' rather '>' to generate valid html fragment for non-closed tag...

### PR DESCRIPTION
**Pull request by liunaijia**
I think it would generate `` rather ``.

### CODE REVIEW

**Comment by nolanw** [comment]
Hello! HTMLReader [serializes per the WHATWG spec](https://html.spec.whatwg.org/#serialising-html-fragments), which does not prescribe a slash in this situation. Is there a particular reason you'd prefer to output the slash? Maybe there's room for some serialization options in HTMLReader.

**Spec chat ahead**

Here's the relevant part of the spec (linked above):

> For each child node of the node, in tree order, run the following steps:
> …
> Append a U+003C LESS-THAN SIGN character (<), followed by tagname.
> For each attribute that the element has, append a U+0020 SPACE character, the attribute's serialised name as described below, a U+003D EQUALS SIGN character (=), a U+0022 QUOTATION MARK character ("), the attribute's value, escaped as described below in attribute mode, and a second U+0022 QUOTATION MARK character (").
> …
> Append a U+003E GREATER-THAN SIGN character (>).
> If current node is an area, base, basefont, bgsound, br, col, embed, frame, hr, img, input, keygen, link, menuitem, meta, param, source, track or wbr element, then continue on to the next child node at this point.

While your change produces entirely valid HTML, I have no plans to stray from the spec here. Sorry about that.

**Comment by liunaijia** [comment]
Hi Nolanw,

Thanks for letting me know that.

I think for a `void element` the slash(`/`) is optional in the start tag for html, you could find the details in section `12.1.2.1 Start tags` on [this page] (https://html.spec.whatwg.org/#serialising-html-fragments).

>Then, if the element is one of the void elements, or if the element is a foreign element, then there may be a single U+002F SOLIDUS character (/). This character has no effect on void elements, but on foreign elements it marks the start tag as self-closing.

However, **the slash is required for `xhtml`**, the details is on [this page] (http://www.w3.org/TR/xhtml1/#h-4.6).

Considering a large number of websites are still built on `xhtml`, so I was wondering whether it would be good to make this as an optional.

**Comment by nolanw** [comment]
You're entirely correct. As far as I know, though, HTMLReader has no problem parsing XHTML, so that "large number of websites" should work great.

HTMLReader does not currently output valid XHTML, but I'm ok with that.

If you or someone else plans on using HTMLReader to serialize XHTML documents, I'd consider adding it as an option. But I'm not aware of anyone trying to do such things. Are you?

**Comment by liunaijia** [comment]
You are right, HTMLReader works fine for both parsing html and xhtml, it is great!

However while the page is written by xhtml and the root element may like this:
`<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">`
If I changed DOM tree and serialized it with HTMLReader for xhtml page, I suppose the `void element` may miss the slash in the start tag, it would not be a well-formed xhtml page.

**Comment by nolanw** [comment]
@liunaijia That's a good point, let me consider whether it's something I want HTMLReader to support.

At the moment, assuming that the serialized output is a valid HTML (not XHTML) document, I'm leaning towards not changing anything in HTMLReader. But I'll think about it first.

**Comment by liunaijia** [comment]
Cool, that would be great, thanks.

**Pull request closed without merging**
