### PR TITLE
Added explicit tvOS support

### PR DESCRIPTION
**Pull request by zoul**
Judging by the podspec file, the library can be built for tvOS via CocoaPods? I had no luck with Carthage, so I have added an explicit build target for tvOS.

### CODE REVIEW

**Comment by zoul** [comment]
I see, the warning fix didn’t work as expected. I’ll take a look at it.

**Comment by zoul** [comment]
I have just uploaded a testing build with the tvOS HTMLReader to the App Store, so the target seems to work fine. Didn’t test on a device yet, though.

**Comment by nolanw** [comment]
Awesome, thank you! I squashed the first and last commit submitted here, and switched the badge to be project-specific (and therefore more likely to stay up-to-date).

Happy to hear of a positive App Store submission!

**Comment by zoul** [comment]
Perfect! Just to be clear, the build was only uploaded to TestFlight in iTunes Connect, we haven’t released the app yet. But even the submission to iTunes Connect is an important milestone.

**Comment by nolanw** [comment]
Understood. I'd love to hear about it once it's in the store and/or you've given it a go on device!

**Pull request closed without merging**
